-- CreateTable
CREATE TABLE `Afbeelding` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `url` VARCHAR(191) NOT NULL,
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `pandId` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Afbeelding` ADD CONSTRAINT `Afbeelding_pandId_fkey` FOREIGN KEY (`pandId`) REFERENCES `Pand`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
